
[[constraint]]
  branch = "master"
  name = "github.com/athoune/yangtze"

[[constraint]]
  name = "github.com/coreos/go-systemd"
  version = "18.0.0"

[[constraint]]
  name = "github.com/davecgh/go-spew"
  version = "1.1.1"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  version = "0.2.0"

[[constraint]]
  name = "github.com/hpcloud/tail"
  version = "1.0.0"

[[constraint]]
  name = "github.com/influxdata/kapacitor"
  version = "1.5.2"

[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/vjeantet/grok"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/mcuadros/go-syslog.v2"
  version = "2.2.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/influxdata/flux"
  version = "~0.21.0"
