
[[constraint]]
  branch = "master"
  name = "github.com/athoune/yangtze"



[[constraint]]
  name = "github.com/mitchellh/mapstructure"
  version = "1.1.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.3.0"

[[constraint]]
  name = "github.com/vjeantet/grok"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/mcuadros/go-syslog.v2"
  version = "2.2.1"

[[constraint]]
  name = "gopkg.in/yaml.v2"
  version = "2.2.2"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/influxdata/flux"
  version = "0.21.2"

[[constraint]]
  branch = "master"
  name = "github.com/containerd/fifo"

[[override]]
  branch = "master"
  name = "github.com/apache/arrow"
