[[constraint]]
  name = "github.com/hpcloud/tail"
  version = "1.0.0"

[[constraint]]
  name = "github.com/vjeantet/grok"
  version = "1.0.0"

[[constraint]]
  name = "gopkg.in/mcuadros/go-syslog.v2"
  version = "2.2.1"

[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.2.1"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "master"
  name = "github.com/athoune/yangtze"

[[constraint]]
  branch = "master"
  name = "github.com/getsentry/raven-go"

[[constraint]]
  name = "github.com/influxdata/kapacitor"
  version = "1.5.1"
