version: '2'

services:
  log:
    image: debian
    ports:
     - 1514
    volumes:
     - ./lepsius:/opt/lepsius:ro
    command: /opt/lepsius

  web:
    image: nginx
    ports:
     - 80

  proxy:
    build: haproxy
    volumes:
     - ./haproxy.cfg:/etc/haproxy/haproxy.cfg:ro
    ports:
     - 8888:8888
    depends_on:
     - log
     - web
